project:
  type: website

website:
  title: "Londogard Blog"
  favicon: favicon.ico
  site-url: https://blog.londogard.com/
  description: "A blog which majorly focuses on Data Science, Data Engineering and sometimes Kotlin / Scala."
  twitter-card:
     creator: "@hlondogard"
  page-footer:
    left:
      - text: "![](https://cdn.buymeacoffee.com/buttons/v2/default-blue.png){width=100}"
        href: https://www.buymeacoffee.com/hlondogard
      - text: "![](https://img.shields.io/static/v1?label=Sponsor&message=%E2%9D%A4&logo=GitHub&color=%23fe8e86){width=100}"
        href: https://github.com/sponsors/Lundez?o=esb
    center:
      - about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/hampus-londögård/
        aria-label: LinkedIn
      - icon: twitter
        href: https://twitter.com/hlondogard
        aria-label: Twitter
      - icon: github
        href: https://github.com/lundez
        aria-label: Lundez GitHub
      - icon: rss
        href: index.xml
        aria-label: Londogard Blog RSS  
  navbar:
      left: 
      - presentations.qmd
      - text: "Londogard Projects↗"
        href: https://londogard.com/projects
      right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/hampus-londögård/
        aria-label: LinkedIn
      - icon: twitter
        href: https://twitter.com/hlondogard
        aria-label: Twitter
      - icon: github
        menu:
          - icon: github
            text: "Lundez"
            href: https://github.com/lundez
          - icon: github
            text: "Londogard"
            href: https://github.com/londogard
      - icon: rss
        href: index.xml
        aria-label: Londogard Blog RSS     

format:
  html:
    theme: cosmo
    css: styles.css
