[tool.ruff]
line-length = 120

[tool.black]
color = true
line-length = 120
target-version = ['py310']
skip-string-normalization = true

[tool.mypy]
# temporarily ignore some files
python_version = '3.10'
show_error_codes = true
follow_imports = 'silent'
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
warn_unused_configs = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_calls = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [] # add untyped-libs
ignore_missing_imports = true